### ISSUE TITLE
Remove useage of Objects.toStringHelper

### ISSUE THREAD

**Issue by dherrman** [bazaarvoice/ostrich#195]
```Objects.toStringHelper``` was deprecated in Guava v18, and was removed in v21 (~June 2016).

```Objects.toStringHelper``` was replaced with ```MoreObjects.toStringHelper```

See https://google.github.io/guava/releases/18.0/api/docs/src-html/com/google/common/base/Objects.html#line.157

**Comment by robbytx** [comment]
See also https://github.com/bazaarvoice/curator-extensions/issues/43

**Comment by robbytx** [comment]
Fixed in 2.0.2
